hf_cache_dir: /data/hf_models # Modify as needed
model_root_dir: /data/hf_models # Modify as needed
data_root_dir: /data # Modify as needed
project_root_dir: /home/projects/eval-medical-dapt # Modify as needed