# Med-Flamingo-9B

name: med-flamingo-9b
path: med-flamingo/med-flamingo
clip_vision_encoder_path: ViT-L-14
clip_vision_encoder_pretrained: openai
lang_encoder_path: /data/llama-v1-weights/7B # Modify as needed
tokenizer_path: /data/llama-v1-weights/7B # Modify as needed
cross_attn_every_n_layers: 4
attn_implementation: flash_attention_2
start_stage: 2
model_max_length: 2048